- name: Get Firewalld Service Status
  ansible.builtin.systemd:
    name: "firewalld"
  register: firewalld_status

- name: Open nfs server service in firewalld when firewalld is active
  firewalld:
    service: nfs
    permanent: yes
    state: enabled
    immediate: yes
  when: firewalld_status.status.ActiveState == 'active'
